// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyQSPSxheFFnyumxtszy1H-hHWROxzjDI',
    appId: '1:790266089462:web:0fc61747eb40c733c101d7',
    messagingSenderId: '790266089462',
    projectId: 'flutterp-prep',
    authDomain: 'flutterp-prep.firebaseapp.com',
    databaseURL: 'https://flutterp-prep-default-rtdb.firebaseio.com',
    storageBucket: 'flutterp-prep.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOGYBmG86nRajGdcp1-Bb5-MZWVpfUAAU',
    appId: '1:790266089462:android:363c5d18d70915d0c101d7',
    messagingSenderId: '790266089462',
    projectId: 'flutterp-prep',
    databaseURL: 'https://flutterp-prep-default-rtdb.firebaseio.com',
    storageBucket: 'flutterp-prep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04-L4CZbCt3b8WmI69XRngxS__rlEXg8',
    appId: '1:790266089462:ios:ca46ab52c16ea9b1c101d7',
    messagingSenderId: '790266089462',
    projectId: 'flutterp-prep',
    databaseURL: 'https://flutterp-prep-default-rtdb.firebaseio.com',
    storageBucket: 'flutterp-prep.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB04-L4CZbCt3b8WmI69XRngxS__rlEXg8',
    appId: '1:790266089462:ios:5f6c3acd549cc918c101d7',
    messagingSenderId: '790266089462',
    projectId: 'flutterp-prep',
    databaseURL: 'https://flutterp-prep-default-rtdb.firebaseio.com',
    storageBucket: 'flutterp-prep.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
